version: '3.4'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: toor
            POSTGRES_DB: hslumodules
            POSTGRES_USER: hslu
        ports:
        - 5432:5432
    admin:    
        image: adminer    
        ports:      
            - "8082:8080"