version: '3.4'

services:
    db:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=hslumodules
            - MYSQL_USER=hslu
            - MYSQL_PASSWORD=toor
        ports:
            - "3366:3306"
    admin:    
        image: adminer    
        ports:      
            - "8082:8080"